stocks:
  - name: "NIFTY 50"
    ticker: "^NSEI"
    threshold: -0.80
    alert_emails:
      - "shettysanjay01@gmail.com"
      - "deek2588@gmail.com"

  - name: "NIFTY MIDCAP 150"
    ticker: "NIFTYMIDCAP150.NS"
    threshold: -0.80
    alert_emails:
      - "shettysanjay01@gmail.com"

  - name: "NIFTY 500"
    ticker: "^CRSLDX"
    threshold: -0.50
    alert_emails:
      - "shettysanjay01@gmail.com"

  - name: "UTI Gold ETF"
    ticker: "GOLDBETA.NS"
    threshold: -0.50
    alert_emails:
      - "shettysanjay01@gmail.com"
      
      
  - name: "Dollar Index"
    ticker: "DX-Y.NYB"
    threshold: -0.50
    alert_emails:
      - "shettysanjay01@gmail.com"
      
  - name: "Gold Futures (Dollar denominated)"
    ticker: "GC=F"
    threshold: -0.50
    alert_emails:
      - "shettysanjay01@gmail.com"
      - "deek2588@gmail.com"

  - name: "VIX India Index"
    ticker: "^INDIAVIX"
    threshold: 5.00
    alert_emails:
      - "shettysanjay01@gmail.com"
