stocks:
  - name: "NIFTY 50"
    ticker: "^NSEI"
    threshold: -1.0
    alert_emails:
      - "shettysanjay01@gmail.com"
  - name: "NIFTY MIDCAP 150"
    ticker: "NIFTYMIDCAP150.NS"
    threshold: -1.5
    alert_emails:
      - "shettysanjay01@gmail.com"
